[package]
name = "jsonresume-rs"
version = "0.1.0"
authors = ["Zexa <zexa@cock.li>"]
description = "Jsonresume spec compliant data structures provider"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
